/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainticketingsystem;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import javax.swing.JOptionPane;


public class TrainTiket extends javax.swing.JFrame {

   
    

    /**
     * Creates new form System
     */

    public TrainTiket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRbstd = new javax.swing.JRadioButton();
        jRbEco = new javax.swing.JRadioButton();
        jRbFirst = new javax.swing.JRadioButton();
        jRbSingle = new javax.swing.JRadioButton();
        jRbReturn = new javax.swing.JRadioButton();
        jRbAdultYes = new javax.swing.JRadioButton();
        jRbChildYes = new javax.swing.JRadioButton();
        JCb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JTextField();
        jlblTax = new javax.swing.JTextField();
        jlblTotal = new javax.swing.JTextField();
        jbtnReset = new javax.swing.JButton();
        jbtnTotal = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlblClass = new javax.swing.JTextField();
        jlblType = new javax.swing.JTextField();
        jlblA = new javax.swing.JTextField();
        jlblC = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jFrom = new javax.swing.JTextField();
        jTo = new javax.swing.JTextField();
        jDate = new javax.swing.JTextField();
        jTime = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jlblTicketNo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jlblPrice = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jlblRoute = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Train Ticketing System\n");

        jLabel2.setFont(new java.awt.Font("Webdings", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Class");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Ticket Type");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Adult");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Child");

        jRbstd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRbstd.setText("Standard");

        jRbEco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRbEco.setText("Economy");

        jRbFirst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRbFirst.setText("First Class");

        jRbSingle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRbSingle.setText("Single");

        jRbReturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRbReturn.setText("Return");

        jRbAdultYes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRbAdultYes.setText("Yes");

        jRbChildYes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRbChildYes.setText("Yes");

        JCb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sylhet", "Chittagong", "Rangpur", " ", " ", " " }));
        JCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCbActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Destination");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRbFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRbEco, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jRbstd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRbReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCb, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRbSingle))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRbAdultYes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jRbChildYes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRbstd)
                            .addComponent(jRbSingle)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRbChildYes)
                            .addComponent(jRbAdultYes))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRbReturn)
                            .addComponent(jRbEco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jRbFirst))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JCb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sub Total");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tax");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Total");

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jlblTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblTotalActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnTotalMouseClicked(evt);
            }
        });
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnExit.setText("exit");
        jbtnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnExitMouseClicked(evt);
            }
        });
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotal)
                    .addComponent(jlblTax)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jlblSubTotal))
                .addGap(75, 75, 75))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnExit)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Class");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ticket Type");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Adult");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Child");

        jlblClass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblClass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("From");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("To");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Date");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Time");

        jFrom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Ticket No");

        jlblTicketNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblTicketNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblTicketNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Price");

        jlblPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Route");

        jlblRoute.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblRoute.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblRoute.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTo, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jDate)
                    .addComponent(jTime)
                    .addComponent(jFrom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTicketNo)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPrice)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblRoute, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addGap(90, 90, 90))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblType, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlblA, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblType, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jlblA)
                    .addComponent(jlblC)
                    .addComponent(jlblClass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblTicketNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlblTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblTotalActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(Color.BLACK);
    }//GEN-LAST:event_formWindowActivated

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jbtnExitMouseClicked

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
      //=====Time================= 
      Calendar timer = Calendar.getInstance();
      timer.getTime();
      SimpleDateFormat tTime = new SimpleDateFormat("hh:mm:ss");
      jTime.setText(tTime.format(timer.getTime()));
      
      //=======Date===========
      SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
      jDate.setText(Tdate.format(timer.getTime()));
      
      jFrom.setText("Dhaka *");
      jTo.setText((String)JCb.getSelectedItem()+ "  *");
      
     //========== Random Number Generator========
      int num1;
      String q1="";
      num1 = 1325 + (int)(Math.random()*4238);
      q1 +=num1 + 1325;
      jlblTicketNo.setText(q1);
      
      jlblRoute.setText("ANY");
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        
        jlblSubTotal.setText(null);
        jlblTax.setText(null);
        jlblTotal.setText(null);
        jlblTicketNo.setText(null);
        jlblRoute.setText(null);
        jlblPrice.setText(null);
        jlblA.setText(null);
        jlblC.setText(null);
        jlblType.setText(null);
        jlblClass.setText(null);
       
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTotalMouseClicked
        // TODO add your handling code here:
        double tax = 19.50;
        double MilesK8 = 25.78;
        double MilesK12 = 25.10;
        double MilesK20 = 45.23;
        double Milesk30 = 55.98;
        double totalcost, eco = 3.85, fclass = 5.60;
        
        if(jRbstd.getText().length()==0||jRbEco.getText().length()==0||jRbFirst.getText().length()==0)
        {
           JOptionPane.showMessageDialog(this, "class is blank");
        }
        else{
        if((jRbstd.isSelected())&& (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",MilesK8 +  totalcost);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("ONE WAY");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
       else if((jRbstd.isSelected())&& (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +  totalcost)*2);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("RETURN");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbstd.isSelected())&& (jRbSingle.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",MilesK8 +  totalcost -18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("ONE WAY");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
        else if((jRbstd.isSelected())&& (jRbReturn.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",((MilesK8 +  totalcost)*2)-18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("RETURN");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
        else if((jRbstd.isSelected())&& (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +  totalcost));
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("SINGLE");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbstd.isSelected())&& (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +  totalcost)*2);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("RETURN");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbstd.isSelected())&& (jRbSingle.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",((MilesK8 +  totalcost) -18));
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("ONE WAY");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
         else if((jRbstd.isSelected())&& (jRbReturn.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",((MilesK8 +  totalcost)*2)-18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("RETURN");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
         else if((jRbstd.isSelected())&& (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",MilesK8 +  totalcost);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("ONE WAY");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbstd.isSelected())&& (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +  totalcost)*2);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("RETURN");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbstd.isSelected())&& (jRbSingle.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",MilesK8 +  totalcost -18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("ONE WAY");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
        else if((jRbstd.isSelected())&& (jRbReturn.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",((MilesK8 +  totalcost)*2)-18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("STD");
            jlblType.setText("RETURN");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
        else if((jRbEco.isSelected())&& (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*(MilesK8+eco))/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8+eco);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",MilesK8 + eco + totalcost);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("ONE WAY");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbEco.isSelected())&& (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*(MilesK8 *2))/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8 *2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +   totalcost)*2);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("RETURN");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbEco.isSelected())&& (jRbSingle.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*(MilesK8+eco))/100;
            String sTax = String.format("%.2f",(totalcost+eco)-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8 +eco);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +eco+  totalcost) -18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("ONE WAY");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
        else if((jRbEco.isSelected())&& (jRbReturn.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*(MilesK8*2))/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8*2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",((MilesK8 +  totalcost)*2)-18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("RETURN");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
        else if((jRbEco.isSelected())&& (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*(MilesK8+eco))/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8+eco);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",MilesK8 + eco + totalcost);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("ONE WAY");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbEco.isSelected())&& (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*(MilesK8*2))/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8*2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +   totalcost)*2);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("RETURN");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbEco.isSelected())&& (jRbSingle.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*(MilesK8+eco))/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8 +eco);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +eco+  totalcost )-18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("ONE WAY");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
        else if((jRbEco.isSelected())&& (jRbReturn.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*(MilesK8*2))/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8*2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",((MilesK8 +  totalcost)*2)-18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("RETURN");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        } 
        else if((jRbEco.isSelected())&& (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*(MilesK8+eco))/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8+eco);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",MilesK8 + eco + totalcost);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("ONE WAY");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbEco.isSelected())&& (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*(MilesK8*2))/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8*2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +   totalcost)*2);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("RETURN");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbEco.isSelected())&& (jRbSingle.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*(MilesK8+eco))/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8 +eco);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",((MilesK8 +eco+  totalcost) -18));
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("ONE WAY");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
        else if((jRbEco.isSelected())&& (jRbReturn.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*(MilesK8*2))/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8*2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",((MilesK8 +  totalcost)*2)-18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("ECONOMIC");
            jlblType.setText("RETURN");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
        else if((jRbFirst.isSelected())&& (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*(MilesK8+fclass))/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8+fclass);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",MilesK8 +  totalcost+fclass);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("ONE WAY");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbFirst.isSelected())&& (jRbSingle.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*(MilesK8+fclass))/100;
            String sTax = String.format("%.2f",(totalcost+fclass)-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8+fclass);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 + fclass + totalcost) -18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("ONE WAY");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
         else if((jRbFirst.isSelected())&& (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8*2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +  totalcost)*2);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("RETURN");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbstd.isSelected())&& (jRbReturn.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Sylhet"))
        {
            totalcost = (tax*(MilesK8*2))/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8 *2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",((MilesK8 +  totalcost)*2)-18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("RETURN");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
        else if((jRbFirst.isSelected())&& (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*(MilesK8+fclass))/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8+fclass);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",MilesK8 +  totalcost+fclass);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("ONE WAY");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbFirst.isSelected())&& (jRbSingle.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*(MilesK8+fclass))/100;
            String sTax = String.format("%.2f",(totalcost+fclass)-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8+fclass);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 + fclass + totalcost )-18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("ONE WAY");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
         else if((jRbFirst.isSelected())&& (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8*2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +  totalcost)*2);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("RETURN");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbFirst.isSelected())&& (jRbReturn.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Chittagong"))
        {
            totalcost = (tax*(MilesK8*2))/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8 *2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",((MilesK8 +  totalcost)*2)-18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("RETURN");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
         else if((jRbFirst.isSelected())&& (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*(MilesK8+fclass))/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8+fclass);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",MilesK8 +  totalcost+fclass);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("ONE WAY");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbFirst.isSelected())&& (jRbSingle.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*(MilesK8+fclass))/100;
            String sTax = String.format("%.2f",(totalcost+fclass)-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8+fclass);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 + fclass + totalcost) -18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("ONE WAY");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
         else if((jRbFirst.isSelected())&& (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*MilesK8)/100;
            String sTax = String.format("%.2f",totalcost);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8*2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",(MilesK8 +  totalcost)*2);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("RETURN");
            jlblA.setText("ONE");
            jlblC.setText("NIL");
        }
        else if((jRbFirst.isSelected())&& (jRbReturn.isSelected()) && (jRbChildYes.isSelected())&&
                JCb.getSelectedItem().equals("Rangpur"))
        {
            totalcost = (tax*(MilesK8*2))/100;
            String sTax = String.format("%.2f",totalcost-18);
            jlblTax.setText(sTax);
            String subTotal = String.format("%.2f",MilesK8 *2);
            jlblSubTotal.setText(subTotal);
            String Total = String.format("$%.2f",((MilesK8 +  totalcost)*2)-18);
            jlblTotal.setText(Total);
            jlblPrice.setText(Total);
            jlblClass.setText("FIRST");
            jlblType.setText("RETURN");
            jlblA.setText("NIL");
            jlblC.setText("ONE");
        }
        }
    }//GEN-LAST:event_jbtnTotalMouseClicked

    private void JCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCb;
    private javax.swing.JTextField jDate;
    private javax.swing.JTextField jFrom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRbAdultYes;
    private javax.swing.JRadioButton jRbChildYes;
    private javax.swing.JRadioButton jRbEco;
    private javax.swing.JRadioButton jRbFirst;
    private javax.swing.JRadioButton jRbReturn;
    private javax.swing.JRadioButton jRbSingle;
    private javax.swing.JRadioButton jRbstd;
    private javax.swing.JTextField jTime;
    private javax.swing.JTextField jTo;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JTextField jlblA;
    private javax.swing.JTextField jlblC;
    private javax.swing.JTextField jlblClass;
    private javax.swing.JTextField jlblPrice;
    private javax.swing.JTextField jlblRoute;
    private javax.swing.JTextField jlblSubTotal;
    private javax.swing.JTextField jlblTax;
    private javax.swing.JTextField jlblTicketNo;
    private javax.swing.JTextField jlblTotal;
    private javax.swing.JTextField jlblType;
    // End of variables declaration//GEN-END:variables
}
